// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateURLRequest create Url request
//
// swagger:model CreateUrlRequest
type CreateURLRequest struct {

	// long Url
	LongURL string `json:"longUrl,omitempty"`
}

// Validate validates this create Url request
func (m *CreateURLRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create Url request based on context it is used
func (m *CreateURLRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateURLRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateURLRequest) UnmarshalBinary(b []byte) error {
	var res CreateURLRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
