// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetURLRequest get Url request
//
// swagger:model GetUrlRequest
type GetURLRequest struct {

	// short Id
	ShortID string `json:"shortId,omitempty"`
}

// Validate validates this get Url request
func (m *GetURLRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get Url request based on context it is used
func (m *GetURLRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetURLRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetURLRequest) UnmarshalBinary(b []byte) error {
	var res GetURLRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
