// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// URLInfo Url info
//
// swagger:model UrlInfo
type URLInfo struct {

	// created
	Created string `json:"created,omitempty"`

	// expires
	Expires string `json:"expires,omitempty"`

	// long Url
	LongURL string `json:"longUrl,omitempty"`

	// short Id
	ShortID string `json:"shortId,omitempty"`
}

// Validate validates this Url info
func (m *URLInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this Url info based on context it is used
func (m *URLInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *URLInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *URLInfo) UnmarshalBinary(b []byte) error {
	var res URLInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
