version: '3'
services:
  mp-redis:
    container_name: mp-redis
    image: redis:5
    restart: always
    ports:
      - "6379:6379"
    networks:
      - tinynet

  mp-mongodb:
    container_name: mp-mongodb
    image: mongo:3.6
    restart: always
    ports:
      - "27017:27017"
    networks:
      - tinynet
    environment:
      MONGO_DATA_DIR: /data/mongodb
      MONGO_LOG_DIR: /data/mongodb/log
    volumes:
      - ~/data/mongodb:/data/mongodb/data
      - ~/data/mongodb/log:/data/mongodb/log
    command: mongod --smallfiles

volumes:
 mongo-data:
networks:
  tinynet:
